# Generated by Django 4.1.3 on 2022-11-07 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_idioma_libro_idioma'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='photos', verbose_name='Foto'),
        ),
    ]
