# Generated by Django 4.1.3 on 2022-11-07 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_libro_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='avatar',
            field=models.ImageField(upload_to='photos', verbose_name='Foto'),
        ),
    ]
