# Generated by Django 4.1.3 on 2022-11-07 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0006_remove_libro_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='fotos', verbose_name='Foto'),
        ),
    ]
