# Generated by Django 4.1.3 on 2022-11-07 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0009_alter_libro_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='photos', verbose_name='Foto'),
        ),
    ]
