# Generated by Django 4.1.3 on 2022-11-19 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0014_autor_foto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='autor',
            options={'ordering': ['apellido', 'nombre']},
        ),
        migrations.AlterModelOptions(
            name='ejemplar',
            options={'ordering': ['fechaDevolucion']},
        ),
    ]
